#!/bin/sh
sudo sh -c "echo 's 7 1366 1060' > /sys/class/drm/card0/device/pp_od_clk_voltage"
sudo sh -c "echo 's 6 1300 1050' > /sys/class/drm/card0/device/pp_od_clk_voltage"
sudo sh -c "echo 's 5 1257 1040' > /sys/class/drm/card0/device/pp_od_clk_voltage"
sudo sh -c "echo 's 5 1257 1040' > /sys/class/drm/card0/device/pp_od_clk_voltage"
sudo sh -c "echo 's 4 1215 1030' > /sys/class/drm/card0/device/pp_od_clk_voltage"
sudo sh -c "echo 's 3 1145 1020' > /sys/class/drm/card0/device/pp_od_clk_voltage"
sudo sh -c "echo 'c' > /sys/class/drm/card0/device/pp_od_clk_voltage"
